name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.4.1
        include-templates: true

    - name: Run tests
      run: ./run_ci.bat
